
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Writing: /blog
  Contact: /contact

# Miscelaneous
favicon: /favicon.ico
excerpt_link: Read

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
-
